# Generated by Django 3.1.4 on 2021-01-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='FechaNacimiento',
            field=models.DateField(null=True),
        ),
    ]
