# Generated by Django 3.1.4 on 2021-01-29 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0002_auto_20210120_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dni', models.CharField(max_length=9, unique=True)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=70)),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=9)),
                ('FechaNacimiento', models.DateField(null=True)),
                ('Rol', models.CharField(default='Cliente', max_length=30)),
                ('Activado', models.BooleanField(default='False')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='coche',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='coche',
            name='Perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nucleo.perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reparacion',
            name='Perfiles',
            field=models.ManyToManyField(related_name='Mecanicos', to='nucleo.Perfil'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.perfil'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='Reparador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.perfil'),
        ),
        migrations.DeleteModel(
            name='Mecanico',
        ),
    ]
