# Generated by Django 3.1.4 on 2021-01-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20210129_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='Dni',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
