# Generated by Django 3.1.4 on 2021-02-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20210129_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='Apellidos',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='Direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='Dni',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='Nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='Telefono',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
