# Generated by Django 3.1.4 on 2021-02-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_auto_20210201_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coche',
            old_name='Colro',
            new_name='Color',
        ),
    ]
