# Generated by Django 3.1.4 on 2021-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_auto_20210202_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='Imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='FechaArreglo',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='Observaciones',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
