# Generated by Django 3.1.4 on 2021-02-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0011_auto_20210203_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='Coches',
        ),
        migrations.AddField(
            model_name='reparacion',
            name='Coches',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nucleo.coche'),
            preserve_default=False,
        ),
    ]
