# Generated by Django 3.1.4 on 2021-02-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_auto_20210206_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problema', models.CharField(max_length=100)),
                ('Texto', models.CharField(max_length=300)),
                ('FechaPeticion', models.DateField()),
                ('EmailUsuario', models.CharField(max_length=100)),
            ],
        ),
    ]
