# Generated by Django 3.1.4 on 2021-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0015_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='coches'),
        ),
    ]
