# Generated by Django 3.1.4 on 2021-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0017_auto_20210208_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='Matricula',
            field=models.CharField(default='hola', max_length=7),
            preserve_default=False,
        ),
    ]
