# Generated by Django 3.1.4 on 2021-02-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0018_coche_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='Atendido',
            field=models.BooleanField(default=False),
        ),
    ]
